#!/usr/bin/env bash
# FizzBuzz implementation
for i in {1..100}
do
    if [ "$(( % 3))" -eq 0 ] && [ "$(( % 5))" -eq 0 ]
    then
        echo -n "FizzBuzz "
    elif [ "$(( % 3))" -eq 0 ]
    then
        echo -n "Fizz "
    elif [ "$(( % 5))" -eq 0 ]
    then
        echo -n "Buzz "
    else
        echo -n " "
    fi
done
echo "