#!/usr/bin/env bash
# This script is a FizzBuzz implementation
for i in {1..100}
do
    if [ $((i % 3)) -eq 0 ] && [ $((i % 5)) -eq 0 ]
    then
        echo -n "FizzBuzz "
    elif [ $((i % 3)) -eq 0 ]
    then
        echo -n "Fizz "
    elif [ $((i % 5)) -eq 0 ]
    then
        echo -n "Buzz "
    else
        echo -n "$i "
    fi
done
echo ""
