#!/usr/bin/env bash
# This script prints the alphabet in reverse except for 'e' and 'q'
for char in {z..a}
do
    if [ "$char" != "e" ] && [ "$char" != "q" ]
    then
        echo -n "$char"
    fi
done
echo ""
