#!/usr/bin/env bash
# Displays all possible combinations of two-digit numbers for hours and minutes
h=0
while [ "" -lt 24 ]
do
    m=0
    while [ "" -lt 60 ]
    do
        printf "%02d:%02d\n" "" ""
        m=
    done
    h=
done