#!/usr/bin/env bash
# This script loops 10 times, says Hi on the 9th, using a while loop
counter=1
while [ "$counter" -le 10 ]
do
    if [ "$counter" -eq 9 ]
    then
        echo "Hi"
    else
        echo "Best School"
    fi
    ((counter++))
done
