#!/usr/bin/env bash
# This script displays Best School 10 times, and once more for the 9th iteration
for ((i=1; i<=10; i++))
do
    echo "Best School"
    if [ $i -eq 9 ]
    then
        echo "Best School"
    fi
done
