#!/usr/bin/env bash
# This script loops from 1 to 10 with specific messages for 4 and 8
counter=1
while [ "$counter" -le 10 ]
do
    echo "Best School"
    if [ "$counter" -eq 4 ]
    then
        echo "bad luck"
    elif [ "$counter" -eq 8 ]
    then
        echo "good luck"
    fi
    ((counter++))
done
