#!/usr/bin/env bash
# This script loops from 1 to 10 and uses a case statement for 4 and 9
counter=1
while [ "$counter" -le 10 ]
do
    case "$counter" in
        4)
            echo "$counter is a superstitious number"
            ;;
        9)
            echo "$counter is a superstitious number"
            ;;
        *)
            echo "$counter"
            ;;
    esac
    ((counter++))
done
