#!/usr/bin/env bash
# This script displays Best School and a message on the 9th iteration
for ((i=1; i<=10; i++))
do
    echo "Best School"
    if [ $i -eq 9 ]
    then
        echo "I love number 9"
    fi
done
