#!/usr/bin/env bash
# This script provides information about the file 'school'
if [ -e "school" ]
then
    echo "school exists"
    if [ -f "school" ]
    then
        echo "school is a regular file"
        if [ -s "school" ]
        then
            echo "school is not empty"
        else
            echo "school is empty"
        fi
    elif [ -d "school" ]
    then
        echo "school is a directory"
    fi
else
    echo "school doesn't exist"
fi
